name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  pytest_and_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Git tag from version.txt
        run: |
          echo "VERSION=$(cat version.txt)"
          git tag $VERSION

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the dependencies
        run: |
          uv sync --extra test

      - name: Run pre-commit checks
        run: |
          uv run pre-commit run --all-files

      - name: Run pytest
        run: |
          uv run pytest -m "not ci_exclude"